name: Upload build project as release assets

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-assets:
    name: Build release assets
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install npm dependencies
        run: npm ci --no-audit --no-progress

      - name: Build project
        run: npm run build

      - name: Compress into Zip file
        run: zip -r -q -9 -X lautfm-exporter_${{ github.ref_name }}.zip dist/ package.json package-lock.json

      - name: Upload zip file as asset
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: lautfm-exporter_${{ github.ref_name }}.zip
